CC=/usr/local/cuda/bin/nvcc
INCLUDE=-I/usr/local/cuda/include \
        -I/usr/local/cuda/samples/common/inc

LIBDIR=-L/usr/local/cuda/lib64
LIBS=-lcudart

SOURCE=sobel.cu
EXECUTABLE=sobel

$(EXECUTABLE): $(SOURCE)
	$(CC) $(INCLUDE) $(LIBDIR) $< -o $@ $(LIBS)

clean:
	rm -rf $(EXECUTABLE)
